
# This a Dockerfile for building all of the ros2 message types for the Indy Autonomous Challenge
# Intended for use playing ros2 bags in ros2 humble

#This base image is quite comprehensive, but there's still a few more things we need
FROM ros:humble-ros-core-jammy

# install bootstrap tools
RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    git \
    python3-colcon-common-extensions \
    python3-colcon-mixin \
    python3-rosdep \
    python3-vcstool \
    && rm -rf /var/lib/apt/lists/*


# install ros2 packages
RUN apt update && apt install -y --no-install-recommends \
    clang \
    libpcl-dev \
    libopencv-dev \
    libgeographic-dev \
    libusb-1.0-0-dev \
    libflann-dev \
    libqhull-dev \
    libalglib-dev \
    libarmadillo-dev \
    libgl1-mesa-dev \
    libpcap-dev \
    libboost-all-dev \
    python3-setuptools \
    python3-pip \
    python3-numpy \
    python3-yaml \
    python3-pillow \
    python3-tqdm \
    python3-matplotlib \
    python3-pandas \
    python3-scipy \
    python3-transforms3d \
    python3-shapely \
    libeigen3-dev \
    ninja-build \
    dos2unix \
    net-tools \
    && rm -rf /var/lib/apt/lists/*

RUN sudo update-alternatives --config cc
RUN sudo update-alternatives --config c++

# COPY scripts/install/install_hum.sh /root/install_hum.sh
# RUN chmod a+x /root/install_hum.sh
# RUN /root/install_hum.sh

COPY ./install_additional_ros_stuff.sh /root/install_additional_ros_stuff.sh
RUN chmod a+x /root/install_additional_ros_stuff.sh
RUN /root/install_additional_ros_stuff.sh

WORKDIR /Dash
COPY ./requirements.txt /root/requirements.txt
RUN pip install -r /root/requirements.txt

RUN mkdir -p /root/.colcon
ADD ./defaults.yaml /root/.colcon/defaults.yaml
ENV DISPLAY:=0